#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""PlatformIO pre-build script: gzip every file under data/ into a single
PROGMEM header (src/web_assets.h) so the web UI ships inside the firmware and a
single OTA updates everything. Never edit web_assets.h by hand."""

import gzip
import os

Import("env")  # noqa: F821  (injected by PlatformIO/SCons)

PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821
DATA_DIR = os.path.join(PROJECT_DIR, "data")
OUT = os.path.join(PROJECT_DIR, "src", "web_assets.h")

CONTENT_TYPES = {
    ".html": "text/html",
    ".css": "text/css",
    ".js": "application/javascript",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".ico": "image/x-icon",
    ".woff2": "font/woff2",
}


def collect(root):
    files = []
    if not os.path.isdir(root):
        return files
    for dirpath, _dirs, names in os.walk(root):
        for name in sorted(names):
            full = os.path.join(dirpath, name)
            rel = "/" + os.path.relpath(full, root).replace(os.sep, "/")
            files.append((rel, full))
    return sorted(files)


def main():
    files = collect(DATA_DIR)
    lines = [
        "// AUTO-GENERATED by scripts/embed_assets.py — do not edit.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "struct WebAsset {",
        "  const char *path;",
        "  const uint8_t *data;",
        "  unsigned len;",
        "  const char *type;",
        "  bool gzip;",
        "};",
        "",
    ]

    entries = []
    for idx, (rel, full) in enumerate(files):
        with open(full, "rb") as fh:
            raw = fh.read()
        packed = gzip.compress(raw, 9)
        ext = os.path.splitext(rel)[1].lower()
        ctype = CONTENT_TYPES.get(ext, "application/octet-stream")
        var = f"asset_{idx}"
        body = ", ".join(str(b) for b in packed)
        lines.append(f"static const uint8_t {var}[] PROGMEM = {{{body}}};")
        entries.append((rel, var, len(packed), ctype))

    lines.append("")
    lines.append("static const WebAsset WEB_ASSETS[] = {")
    for rel, var, length, ctype in entries:
        lines.append(f'  {{"{rel}", {var}, {length}, "{ctype}", true}},')
    lines.append("};")
    lines.append(f"static const unsigned WEB_ASSETS_COUNT = {len(entries)};")
    lines.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    print(f"embed_assets: {len(entries)} file(s) -> {os.path.relpath(OUT, PROJECT_DIR)}")


main()
